/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'
import { useRef, useState } from 'react';
import { useFrame } from 'react-three-fiber';
import { SpotLightHelper , SpotLight } from 'three';
export default function Scene({ ...props }) {
  const [pos,setPos] = useState('')
  const { nodes, materials } = useSpline('https://prod.spline.design/5iOG-WBGIXAKZgqD/scene.splinecode')

  return (
    <>
      <color attach="background" args={['#eae7e3']} />
      <group {...props} dispose={null}>
      <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.8}
          shadow-mapSize-width={4096}
          shadow-mapSize-height={4096}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-1299.8485}
          shadow-camera-right={1299.8485}
          shadow-camera-top={1299.8485}
          shadow-camera-bottom={-1299.8485}
          color="#f2e6db"
          position={[-576, 1249.29, 683.88]}
        />
        <mesh
          name="Floor"
          geometry={nodes.Floor.geometry}
          material={materials['Floor Material']}
          castShadow
          receiveShadow
          position={[0, -410, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1}
        />
        
     
        <group name="geo" position={[0, 200, -600]}
       
       >
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials['Color 4']}
            castShadow
            receiveShadow
            position={[-8.65, 347.56, 466.75]}
          />
          <mesh
            name="Cube 11"
            geometry={nodes['Cube 11'].geometry}
            material={materials['Color 1']}
            castShadow
            receiveShadow
            position={[-12.65, 444.49, 255.63]}
            rotation={[0.04, 0, -Math.PI]}
            scale={[1.03, 0.3, 0.63]}
          />
          <mesh
            name="Cube 4"
            geometry={nodes['Cube 4'].geometry}
            material={materials['Color 3']}
            castShadow
            receiveShadow
            position={[-12.65, 440.05, 255.43]}
            rotation={[0.04, 0, -Math.PI]}
            scale={[1.02, 0.3, 0.63]}
          />
          <mesh
            name="Cube 12"
            geometry={nodes['Cube 12'].geometry}
            material={materials['Color 5']}
            castShadow
            receiveShadow
            position={[-10.65, 207.68, 444.22]}
            rotation={[0.05, 0, 0]}
            scale={[1, 1.06, 0.14]}
          />
          <mesh
            name="Cube 2"
            geometry={nodes['Cube 2'].geometry}
            material={materials['Color 3']}
            castShadow
            receiveShadow
            position={[-11.59, 222.53, 438.91]}
            scale={[1, 1.06, 0.16]}
          />
          <mesh
            name="Cube 15"
            geometry={nodes['Cube 15'].geometry}
            material={materials['Color 3']}
            castShadow
            receiveShadow
            position={[-12.43, 272.7, 267.48]}
            rotation={[-1.52, Math.PI / 2, 0]}
            scale={[1.67, 1.64, 1.58]}
          />
          <mesh
            name="Cube 10"
            geometry={nodes['Cube 10'].geometry}
            material={materials['Color 1']}
            castShadow
            receiveShadow
            position={[-12.43, 272.7, 267.48]}
            rotation={[-1.52, Math.PI / 2, 0]}
            scale={[1.65, 1.61, 1.56]}
          />
          <mesh
            name="Cube 16"
            geometry={nodes['Cube 16'].geometry}
            material={materials['Color 1']}
            castShadow
            receiveShadow
            position={[-12.43, 275.37, 259.48]}
            rotation={[-1.52, Math.PI / 2, 0]}
            scale={[1.6, 1.6, 1.5]}
          />
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials['Color 2']}
            castShadow
            receiveShadow
            position={[-12.43, 274.93, 267.6]}
            rotation={[-1.52, Math.PI / 2, 0]}
            scale={[1.6, 1.52, 1.5]}
          />
          <mesh
            name="Cube 14"
            geometry={nodes['Cube 14'].geometry}
            material={materials['Color 3']}
            castShadow
            receiveShadow
            position={[-10.9, 332.37, 442.4]}
            scale={[0.71, 1.04, 0.14]}
          />
          <mesh
            name="Cube 7"
            geometry={nodes['Cube 7'].geometry}
            material={materials['Color 1']}
            castShadow
            receiveShadow
            position={[-10.9, 332.37, 437.55]}
            scale={[0.71, 1.04, 0.14]}
          />
          <group name="Group 19" position={[281.8, 17.73, -430.87]} scale={[-1.12, 1, 1]}>
            <mesh
              name="Cylinder 4"
              geometry={nodes['Cylinder 4'].geometry}
              material={materials['Color 8']}
              castShadow
              receiveShadow
              position={[26.62, 85.35, -30.43]}
              rotation={[-2.45, 0, 0]}
              scale={0.17}
            />
          </group>
          <group name="Group 18" position={[-304.08, 17.73, -430.87]}>
            <mesh
              name="Cylinder 41"
              geometry={nodes['Cylinder 41'].geometry}
              material={materials['Color 8']}
              castShadow
              receiveShadow
              position={[26.62, 85.35, -30.43]}
              rotation={[-2.45, 0, 0]}
              scale={0.17}
            />
          </group>
          <group name="Group 17" position={[-267.65, 123.84, -266.25]} scale={[-0.83, 1, 1]}>
            <mesh
              name="Cylinder 42"
              geometry={nodes['Cylinder 42'].geometry}
              material={materials['Color 8']}
              castShadow
              receiveShadow
              position={[4.7, -22.97, -16.27]}
              rotation={[0.05, 1.27, -Math.PI / 2]}
              scale={[0.2, 2.35, 0.2]}
            />
          </group>
          <group name="Group 16" position={[230.34, 112.05, -266.25]}>
            <mesh
              name="Cylinder 43"
              geometry={nodes['Cylinder 43'].geometry}
              material={materials['Color 8']}
              castShadow
              receiveShadow
              position={[4.7, -22.97, -16.27]}
              rotation={[0.08, 1.43, -1.71]}
              scale={[0.2, 2.35, 0.2]}
            />
          </group>
          <mesh
            name="Cylinder 3"
            geometry={nodes['Cylinder 3'].geometry}
            material={materials['Color 5']}
            castShadow
            receiveShadow
            position={[90.79, 523.96, 188.76]}
            rotation={[0, 0, 0]}
            scale={[0.03, 2.43, 0.03]}
          />
          <mesh
            name="Cylinder 2"
            geometry={nodes['Cylinder 2'].geometry}
            material={materials['Color 5']}
            castShadow
            receiveShadow
            position={[90.79, 485.77, 237.13]}
            rotation={[0, 0, 0]}
            scale={[0.03, 1.27, 0.03]}
          />
          <group name="Group 15" position={[-265.71, 194.16, -182.15]} scale={[-0.98, 1, 1]}>
            <mesh
              name="Cube 71"
              geometry={nodes['Cube 71'].geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[-11.92, 48.7, 16.11]}
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.57, 1, 1]}
            />
          </group>
          <mesh
            name="Cube 6"
            geometry={nodes['Cube 6'].geometry}
            material={materials['Color 5']}
            castShadow
            receiveShadow
            position={[228.66, 242.86, -166.03]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={[0.57, 1, 1]}
          />
          <group name="Group 14" position={[-294.48, 9.47, -340.55]} scale={[-0.79, 1, 1]}>
            <mesh
              name="Cube 61"
              geometry={nodes['Cube 61'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[-25.72, 58.49, 1.27]}
              rotation={[-0.15, -0.14, 0]}
              scale={1}
            />
          </group>
          <group name="Group 13" position={[265.5, 9.47, -340.55]}>
            <mesh
              name="Cube 62"
              geometry={nodes['Cube 62'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[-25.72, 58.49, 1.27]}
              rotation={[-0.15, -0.14, 0]}
              scale={1}
            />
          </group>
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials['Color 1']}
            castShadow
            receiveShadow
            position={[-14.65, 100.98, 29.15]}
            rotation={[0.05, 0, -Math.PI / 2]}
            scale={[1.98, 1.65, 1.98]}
          />
          <mesh
            name="Cube 5"
            geometry={nodes['Cube 5'].geometry}
            material={materials['Color 2']}
            castShadow
            receiveShadow
            position={[-11.51, 246.94, -121.45]}
            rotation={[-2.95, 0, Math.PI / 2]}
            scale={[0.94, 1.57, 1.09]}
          />
          <group name="Group 12" position={[-11.2, 158.2, -168.61]}>
            <mesh
              name="Cube 121"
              geometry={nodes['Cube 121'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[300.79, -58.35, 168.87]}
              rotation={[0.76, -Math.PI / 2, 0]}
              scale={[0.67, 0.37, 0.16]}
            />
            <mesh
              name="Cube 111"
              geometry={nodes['Cube 111'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[-308.14, -54.79, 172.27]}
              rotation={[0.76, -Math.PI / 2, 0]}
              scale={[0.67, 0.37, 0.16]}
            />
            <group
              name="Group 10"
              position={[274.11, -53.68, 29.34]}
              rotation={[2.4, 0, 0]}
              scale={[-1.07, 1.01, 1.01]}
            >
              <mesh
                name="Cylinder 9"
                geometry={nodes['Cylinder 9'].geometry}
                material={materials['Color 1']}
                castShadow
                receiveShadow
                position={[-6.82, -1.42, -0.96]}
                rotation={[-2.55, 0, Math.PI / 2]}
                scale={[0.45, 0.13, 0.45]}
              />
              <mesh
                name="Cube 51"
                geometry={nodes['Cube 51'].geometry}
                material={materials['Color 3']}
                castShadow
                receiveShadow
                position={[-18.96, -187.68, 33.26]}
                rotation={[2.56, 0, 0]}
                scale={[0.8, 0.8, 0.62]}
              />
              <group name="Group 51" position={[76.98, 0, 0]} scale={[-0.89, 1, 1]}>
                <mesh
                  name="Cylinder 91"
                  geometry={nodes['Cylinder 91'].geometry}
                  material={materials['Color 1']}
                  castShadow
                  receiveShadow
                  position={[-6.82, -1.42, -0.96]}
                  rotation={[-2.55, 0, Math.PI / 2]}
                  scale={[0.45, 0.13, 0.45]}
                />
                <mesh
                  name="Cylinder 8"
                  geometry={nodes['Cylinder 8'].geometry}
                  material={materials['Color 5']}
                  castShadow
                  receiveShadow
                  position={[4.93, 0, 0]}
                  rotation={[-2.55, 0, Math.PI / 2]}
                  scale={[0.8, 0.19, 0.8]}
                />
              </group>
              <mesh
                name="Cylinder 81"
                geometry={nodes['Cylinder 81'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[4.93, 0, 0]}
                rotation={[-2.55, 0, Math.PI / 2]}
                scale={[0.8, 0.19, 0.8]}
              >
                <mesh
                  name="Cube 122"
                  geometry={nodes['Cube 122'].geometry}
                  material={materials['Color 2']}
                  castShadow
                  receiveShadow
                  position={[-3.16, -180.46, -43.85]}
                  rotation={[-Math.PI / 2, 0, 0.09]}
                  scale={[1.91, 0.81, 10]}
                />
              </mesh>
            </group>
            <group name="Group 11" position={[-1.42, -17.93, 46.13]}>
              <group name="Group 52" position={[-274.86, -35.75, -16.79]} rotation={[2.4, 0, 0]} scale={1.01}>
                <mesh
                  name="Cylinder 10"
                  geometry={nodes['Cylinder 10'].geometry}
                  material={materials['Color 2']}
                  castShadow
                  receiveShadow
                  position={[563.11, 96.78, -98.49]}
                  rotation={[-2.4, 0, -Math.PI / 2]}
                  scale={[-2.23, 0.44, 2.23]}
                />
                <mesh
                  name="Cylinder 82"
                  geometry={nodes['Cylinder 82'].geometry}
                  material={materials['Color 2']}
                  castShadow
                  receiveShadow
                  position={[-18.28, 96.78, -98.49]}
                  rotation={[-2.4, 0, Math.PI / 2]}
                  scale={[-2.23, 0.44, 2.23]}
                />
                <mesh
                  name="Cylinder 92"
                  geometry={nodes['Cylinder 92'].geometry}
                  material={materials['Color 2']}
                  castShadow
                  receiveShadow
                  position={[488.96, 96.78, -98.49]}
                  rotation={[-2.4, 0, Math.PI / 2]}
                  scale={[-2.48, 0.49, 2.48]}
                />
                <mesh
                  name="Cylinder 83"
                  geometry={nodes['Cylinder 83'].geometry}
                  material={materials['Color 1']}
                  castShadow
                  receiveShadow
                  position={[21.23, 96.78, -98.49]}
                  rotation={[-2.4, 0, Math.PI / 2]}
                  scale={[-2.48, 0.49, 2.48]}
                />
                <mesh
                  name="Cylinder 93"
                  geometry={nodes['Cylinder 93'].geometry}
                  material={materials['Color 1']}
                  castShadow
                  receiveShadow
                  position={[530.72, 96.78, -98.49]}
                  rotation={[-2.4, 0, Math.PI / 2]}
                  scale={[-2.48, 0.49, 2.48]}
                />
                <mesh
                  name="Cylinder 84"
                  geometry={nodes['Cylinder 84'].geometry}
                  material={materials['Color 3']}
                  castShadow
                  receiveShadow
                  position={[62.99, 96.78, -98.49]}
                  rotation={[-2.4, 0, Math.PI / 2]}
                  scale={[-2.48, 0.49, 2.48]}
                />
                <mesh
                  name="Cylinder 85"
                  geometry={nodes['Cylinder 85'].geometry}
                  material={materials['Color 5']}
                  castShadow
                  receiveShadow
                  position={[271.72, 94.32, -97.17]}
                  rotation={[-2.4, 0, -Math.PI / 2]}
                  scale={[0.85, 2.46, 0.85]}
                />
                <mesh
                  name="Cylinder 94"
                  geometry={nodes['Cylinder 94'].geometry}
                  material={materials['Color 1']}
                  castShadow
                  receiveShadow
                  position={[-6.82, -1.42, -0.96]}
                  rotation={[-2.55, 0, Math.PI / 2]}
                  scale={[0.45, 0.13, 0.45]}
                />
                <mesh
                  name="Cube 52"
                  geometry={nodes['Cube 52'].geometry}
                  material={materials['Color 2']}
                  castShadow
                  receiveShadow
                  position={[-18.96, -187.68, 33.26]}
                  rotation={[2.56, 0, 0]}
                  scale={[0.8, 0.8, 0.62]}
                />
                <group name="Group 53" position={[73.43, 0, 0]} scale={[-1.01, 1, 1]}>
                  <mesh
                    name="Cylinder 95"
                    geometry={nodes['Cylinder 95'].geometry}
                    material={materials['Color 1']}
                    castShadow
                    receiveShadow
                    position={[-6.82, -1.42, -0.96]}
                    rotation={[-2.55, 0, Math.PI / 2]}
                    scale={[0.45, 0.13, 0.45]}
                  />
                  <mesh
                    name="Cylinder 86"
                    geometry={nodes['Cylinder 86'].geometry}
                    material={materials['Color 5']}
                    castShadow
                    receiveShadow
                    position={[4.93, 0, 0]}
                    rotation={[-2.55, 0, Math.PI / 2]}
                    scale={[0.8, 0.19, 0.8]}
                  />
                </group>
                <mesh
                  name="Cylinder 87"
                  geometry={nodes['Cylinder 87'].geometry}
                  material={materials['Color 5']}
                  castShadow
                  receiveShadow
                  position={[4.93, 0, 0]}
                  rotation={[-2.55, 0, Math.PI / 2]}
                  scale={[0.8, 0.19, 0.8]}
                >
                  <mesh
                    name="Cube 123"
                    geometry={nodes['Cube 123'].geometry}
                    material={materials['Color 3']}
                    castShadow
                    receiveShadow
                    position={[-3.16, -180.46, -43.85]}
                    rotation={[-Math.PI / 2, 0, 0.09]}
                    scale={[1.91, 0.81, 9.36]}
                  />
                </mesh>
              </group>
            </group>
          </group>
          <group name="Group 9" position={[280.86, 41.51, -397.61]} scale={[-1.03, 1, 1]}>
            <mesh
              name="Cylinder 44"
              geometry={nodes['Cylinder 44'].geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[-36.22, -224.92, 70.56]}
              rotation={[1.68, 0, -1.52]}
              scale={[1.38, 2.31, 1.38]}
            />
            <mesh
              name="Cube 53"
              geometry={nodes['Cube 53'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[34.43, 68.37, -1.63]}
              rotation={[0.1, 0, 0]}
              scale={[0.86, 1, 0.55]}
            />
            <mesh
              name="Cylinder 31"
              geometry={nodes['Cylinder 31'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[90.87, 187.56, 19.3]}
              rotation={[0.1, 0, -Math.PI / 2]}
              scale={[-0.66, 0.18, 0.66]}
            />
            <mesh
              name="Cylinder 21"
              geometry={nodes['Cylinder 21'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[-23.83, 187.56, 19.3]}
              rotation={[0.1, 0, Math.PI / 2]}
              scale={[0.66, 0.21, 0.66]}
            />
            <mesh
              name="Cylinder 6"
              geometry={nodes['Cylinder 6'].geometry}
              material={materials['Cylinder 6 Material']}
              castShadow
              receiveShadow
              position={[23.05, -226.72, 71.2]}
              rotation={[0.1, 0, -Math.PI / 2]}
              scale={[-0.3, 0.1, 0.3]}
            />
            <mesh
              name="Cylinder 5"
              geometry={nodes['Cylinder 5'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[-98.18, -226.7, 65.54]}
              rotation={[0.1, 0, Math.PI / 2]}
              scale={[0.31, 0.11, 0.31]}
            />
            <group name="Group 7" position={[67.51, 129.36, -60.33]} scale={[-1.08, 1, 1]}>
              <mesh
                name="Cylinder 45"
                geometry={nodes['Cylinder 45'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[-16.04, 0, 0]}
                rotation={[0.1, 0, Math.PI / 2]}
                scale={[0.29, 0.09, 0.29]}
              />
              <mesh
                name="Cylinder 46"
                geometry={nodes['Cylinder 46'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[9.76, 0, 0]}
                rotation={[0.1, 0, Math.PI / 2]}
                scale={[0.29, 0.15, 0.29]}
              />
            </group>
            <group name="Group 6" position={[9.6, 129.36, -60.33]} scale={[1.13, 1, 1]}>
              <mesh
                name="Cylinder 47"
                geometry={nodes['Cylinder 47'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[-16.04, 0, 0]}
                rotation={[0.1, 0, Math.PI / 2]}
                scale={[0.29, 0.09, 0.29]}
              />
              <mesh
                name="Cylinder 48"
                geometry={nodes['Cylinder 48'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[9.76, 0, 0]}
                rotation={[0.1, 0, Math.PI / 2]}
                scale={[0.29, 0.15, 0.29]}
              />
            </group>
            <mesh
              name="Cylinder1"
              geometry={nodes.Cylinder1.geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[34.21, 187.56, 19.3]}
              rotation={[0.1, 0, Math.PI / 2]}
              scale={[0.65, 0.35, 0.65]}
            />
          </group>
          <group name="Group 8" position={[-313.41, 41.51, -397.61]}>
            <mesh
              name="Cylinder 49"
              geometry={nodes['Cylinder 49'].geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[-36.22, -224.92, 70.56]}
              rotation={[1.68, 0, -1.52]}
              scale={[1.38, 2.31, 1.38]}
            />
            <mesh
              name="Cube 54"
              geometry={nodes['Cube 54'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[34.43, 68.37, -1.63]}
              rotation={[0.1, 0, 0]}
              scale={[0.86, 1, 0.55]}
            />
            <mesh
              name="Cylinder 32"
              geometry={nodes['Cylinder 32'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[90.87, 187.56, 19.3]}
              rotation={[0.1, 0, -Math.PI / 2]}
              scale={[-0.66, 0.18, 0.66]}
            />
            <mesh
              name="Cylinder 22"
              geometry={nodes['Cylinder 22'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[-23.83, 187.56, 19.3]}
              rotation={[0.1, 0, Math.PI / 2]}
              scale={[0.66, 0.21, 0.66]}
            />
            <mesh
              name="Cylinder 61"
              geometry={nodes['Cylinder 61'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[23.05, -226.72, 71.2]}
              rotation={[0.1, 0, -Math.PI / 2]}
              scale={[-0.3, 0.1, 0.3]}
            />
            <mesh
              name="Cylinder 51"
              geometry={nodes['Cylinder 51'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[-98.18, -226.7, 65.54]}
              rotation={[0.1, 0, Math.PI / 2]}
              scale={[0.31, 0.11, 0.31]}
            />
            <group name="Group 71" position={[67.51, 129.36, -60.33]} scale={[-1.08, 1, 1]}>
              <mesh
                name="Cylinder 410"
                geometry={nodes['Cylinder 410'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[-16.04, 0, 0]}
                rotation={[0.1, 0, Math.PI / 2]}
                scale={[0.29, 0.09, 0.29]}
              />
              <mesh
                name="Cylinder 411"
                geometry={nodes['Cylinder 411'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[9.76, 0, 0]}
                rotation={[0.1, 0, Math.PI / 2]}
                scale={[0.29, 0.15, 0.29]}
              />
            </group>
            <group name="Group 61" position={[9.6, 129.36, -60.33]} scale={[1.13, 1, 1]}>
              <mesh
                name="Cylinder 412"
                geometry={nodes['Cylinder 412'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[-16.04, 0, 0]}
                rotation={[0.1, 0, Math.PI / 2]}
                scale={[0.29, 0.09, 0.29]}
              />
              <mesh
                name="Cylinder 413"
                geometry={nodes['Cylinder 413'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[9.76, 0, 0]}
                rotation={[0.1, 0, Math.PI / 2]}
                scale={[0.29, 0.15, 0.29]}
              />
            </group>
            <mesh
              name="Cylinder2"
              geometry={nodes.Cylinder2.geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[34.21, 187.56, 19.3]}
              rotation={[0.1, 0, Math.PI / 2]}
              scale={[0.65, 0.35, 0.65]}
            />
          </group>
          <group name="Group 4" position={[232.75, -116.56, 411.2]} scale={[-1.03, 1, 1]}>
            <group name="Group 3" position={[46.74, 103.97, -9.53]} scale={[-0.89, 1, 1]}>
              <mesh
                name="Cylinder 96"
                geometry={nodes['Cylinder 96'].geometry}
                material={materials['Color 1']}
                castShadow
                receiveShadow
                position={[-6.82, -1.42, -0.96]}
                rotation={[-2.55, 0, Math.PI / 2]}
                scale={[0.45, 0.13, 0.45]}
              />
              <mesh
                name="Cylinder 88"
                geometry={nodes['Cylinder 88'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[4.93, 0, 0]}
                rotation={[-2.55, 0, Math.PI / 2]}
                scale={[0.8, 0.19, 0.8]}
              />
            </group>
            <group name="Group 31" position={[-30.24, 103.97, -9.53]}>
              <mesh
                name="Cylinder 97"
                geometry={nodes['Cylinder 97'].geometry}
                material={materials['Color 1']}
                castShadow
                receiveShadow
                position={[-6.82, -1.42, -0.96]}
                rotation={[-2.55, 0, Math.PI / 2]}
                scale={[0.45, 0.13, 0.45]}
              />
              <mesh
                name="Cylinder 89"
                geometry={nodes['Cylinder 89'].geometry}
                material={materials['Color 5']}
                castShadow
                receiveShadow
                position={[4.93, 0, 0]}
                rotation={[-2.55, 0, Math.PI / 2]}
                scale={[0.8, 0.19, 0.8]}
              />
            </group>
            <mesh
              name="Cube 9"
              geometry={nodes['Cube 9'].geometry}
              material={materials['Cube 9 Material']}
              castShadow
              receiveShadow
              position={[8.25, 86.48, 20.9]}
              rotation={[2.08, -Math.PI / 2, 0]}
              scale={[1.52, 0.64, 2.19]}
            />
            <mesh
              name="Cube 91"
              geometry={nodes['Cube 91'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[-20.98, -94.81, 76.78]}
              rotation={[0.85, 0, 0]}
              scale={[1.19, 1.4, 1.05]}
            />
          </group>
          <group name="Group 2" position={[-212.57, -12.58, 401.67]} scale={[-0.89, 1, 1]}>
            <mesh
              name="Cylinder 98"
              geometry={nodes['Cylinder 98'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[-6.82, -1.42, -0.96]}
              rotation={[-2.55, 0, Math.PI / 2]}
              scale={[0.45, 0.13, 0.45]}
            />
            <mesh
              name="Cylinder 810"
              geometry={nodes['Cylinder 810'].geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[4.93, 0, 0]}
              rotation={[-2.55, 0, Math.PI / 2]}
              scale={[0.8, 0.19, 0.8]}
            />
          </group>
          <group name="Group" position={[-289.55, -12.58, 401.67]} scale={1}>
            <mesh
              name="Cylinder 99"
              geometry={nodes['Cylinder 99'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[-6.82, -1.42, -0.96]}
              rotation={[-2.55, 0, Math.PI / 2]}
              scale={[0.45, 0.13, 0.45]}
            />
            <mesh
              name="Cylinder 811"
              geometry={nodes['Cylinder 811'].geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[4.93, 0, 0]}
              rotation={[-2.55, 0, Math.PI / 2]}
              scale={[0.8, 0.19, 0.8]}
            />
          </group>
          <mesh
            name="Cylinder 7"
            geometry={nodes['Cylinder 7'].geometry}
            material={materials['Cylinder 7 Material']}
            castShadow
            receiveShadow
            position={[257.13, -184.22, 519.14]}
            rotation={[-0.75, Math.PI / 2, 0]}
            scale={[0.53, 0.28, 0.37]}
          />
          <mesh
            name="Cylinder 62"
            geometry={nodes['Cylinder 62'].geometry}
            material={materials['Cylinder 62 Material']}
            castShadow
            receiveShadow
            position={[-277.05, -184.22, 519.14]}
            rotation={[-0.75, Math.PI / 2, 0]}
            scale={[0.53, 0.28, 0.37]}
          />
          <mesh
            name="Cube 8"
            geometry={nodes['Cube 8'].geometry}
            material={materials['Cube 8 Material']}
            castShadow
            receiveShadow
            position={[-251.06, -30.06, 432.11]}
            rotation={[2.08, -Math.PI / 2, 0]}
            scale={[1.52, 0.64, 2.19]}
          />
          <mesh
            name="Cube 17"
            geometry={nodes['Cube 17'].geometry}
            material={materials['Color 3']}
            castShadow
            receiveShadow
            position={[285.82, 72.41, 287.23]}
            rotation={[1.39, -Math.PI / 2, 0]}
            scale={[0.64, 0.34, 0.16]}
          />
          <mesh
            name="Cube 72"
            geometry={nodes['Cube 72'].geometry}
            material={materials['Color 3']}
            castShadow
            receiveShadow
            position={[-323.1, 61.67, 289.2]}
            rotation={[1.39, -Math.PI / 2, 0]}
            scale={[0.64, 0.34, 0.16]}
          />
          <mesh
            name="Cube 92"
            geometry={nodes['Cube 92'].geometry}
            material={materials['Color 3']}
            castShadow
            receiveShadow
            position={[221.96, 14.11, 375.67]}
            rotation={[2.16, 0, 0]}
            scale={[0.47, 0.71, 0.39]}
          />
          <mesh
            name="Cube 63"
            geometry={nodes['Cube 63'].geometry}
            material={materials['Color 3']}
            castShadow
            receiveShadow
            position={[-252.44, 14.11, 375.67]}
            rotation={[2.16, 0, 0]}
            scale={[0.47, 0.71, 0.39]}
          />
          <mesh
            name="Cube 55"
            geometry={nodes['Cube 55'].geometry}
            material={materials['Color 2']}
            castShadow
            receiveShadow
            position={[-280.3, -211.38, 487.99]}
            rotation={[0.85, 0, 0]}
            scale={[1.19, 1.4, 1.05]}
          />
          <mesh
            name="Cylinder 52"
            geometry={nodes['Cylinder 52'].geometry}
            material={materials['Color 2']}
            castShadow
            receiveShadow
            position={[-313.34, 70.03, 289.69]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[-2.34, 0.47, 2.34]}
          />
          <mesh
            name="Cylinder 414"
            geometry={nodes['Cylinder 414'].geometry}
            material={materials['Color 2']}
            castShadow
            receiveShadow
            position={[277.04, 70.03, 289.69]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[2.34, 0.44, 2.34]}
          />
          <mesh
            name="Cylinder 53"
            geometry={nodes['Cylinder 53'].geometry}
            material={materials['Color 1']}
            castShadow
            receiveShadow
            position={[-274.91, 70.03, 289.69]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[-2.34, 0.47, 2.34]}
          />
          <mesh
            name="Cylinder 33"
            geometry={nodes['Cylinder 33'].geometry}
            material={materials['Color 1']}
            castShadow
            receiveShadow
            position={[240.62, 70.03, 289.69]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[2.34, 0.44, 2.34]}
          />
          <mesh
            name="Cylinder 54"
            geometry={nodes['Cylinder 54'].geometry}
            material={materials['Color 2']}
            castShadow
            receiveShadow
            position={[-235.47, 70.03, 289.69]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[-2.34, 0.47, 2.34]}
          />
          <mesh
            name="Cylinder 23"
            geometry={nodes['Cylinder 23'].geometry}
            material={materials['Color 2']}
            castShadow
            receiveShadow
            position={[203.24, 70.03, 289.69]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[2.34, 0.44, 2.34]}
          />
          <mesh
            name="Cylinder3"
            geometry={nodes.Cylinder3.geometry}
            material={materials['Color 5']}
            castShadow
            receiveShadow
            position={[-1.43, 65.57, 287.2]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.8, 2.33, 0.8]}
          />
          <group name="Group 72" position={[153.7, 349.95, -111.55]}>
            <mesh
              name="Cylinder 910"
              geometry={nodes['Cylinder 910'].geometry}
              material={materials['Color 8']}
              castShadow
              receiveShadow
              position={[42.49, -4.62, 97.34]}
              rotation={[0.01, 0.14, 1.56]}
              scale={0.55}
            />
            <mesh
              name="Cylinder 812"
              geometry={nodes['Cylinder 812'].geometry}
              material={materials['Color 8']}
              castShadow
              receiveShadow
              position={[28.93, 4.07, -2.2]}
              rotation={[0.01, 0.14, 1.56]}
              scale={0.55}
            />
            <mesh
              name="Cylinder 71"
              geometry={nodes['Cylinder 71'].geometry}
              material={materials['Color 8']}
              castShadow
              receiveShadow
              position={[15.89, 5.21, -97.34]}
              rotation={[0.01, 0.14, 1.56]}
              scale={0.55}
            />
            <mesh
              name="Cylinder 63"
              geometry={nodes['Cylinder 63'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[-19.72, 2.48, -92.83]}
              rotation={[-0.02, 0.16, -1.43]}
              scale={[0.16, 0.67, 0.16]}
            />
            <mesh
              name="Cylinder 55"
              geometry={nodes['Cylinder 55'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[-3.49, 1.14, 1.81]}
              rotation={[-0.02, 0.16, -1.43]}
              scale={[0.16, 0.67, 0.16]}
            />
            <mesh
              name="Cylinder 15"
              geometry={nodes['Cylinder 15'].geometry}
              material={materials['Color 8']}
              castShadow
              receiveShadow
              position={[-339.27, 1.03, -95.26]}
              rotation={[-0.09, -0.17, -1.54]}
              scale={[0.21, 0.26, 0.21]}
            />
            <mesh
              name="Cylinder 12"
              geometry={nodes['Cylinder 12'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[-296.81, 1.51, -87.51]}
              rotation={[-0.09, -0.17, -1.54]}
              scale={[0.16, 0.67, 0.16]}
            />
            <mesh
              name="Cylinder 14"
              geometry={nodes['Cylinder 14'].geometry}
              material={materials['Color 8']}
              castShadow
              receiveShadow
              position={[-354.65, -3.42, 1.6]}
              rotation={[-0.09, -0.17, -1.54]}
              scale={[0.22, 0.26, 0.22]}
            />
            <mesh
              name="Cylinder 11"
              geometry={nodes['Cylinder 11'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[-314.26, -3.04, 9]}
              rotation={[-0.09, -0.17, -1.54]}
              scale={[0.16, 0.67, 0.16]}
            />
            <mesh
              name="Cylinder 13"
              geometry={nodes['Cylinder 13'].geometry}
              material={materials['Color 8']}
              castShadow
              receiveShadow
              position={[-368.42, -3.18, 96.58]}
              rotation={[-0.09, -0.17, -1.54]}
              scale={[0.25, 0.23, 0.25]}
            />
            <mesh
              name="Cylinder 101"
              geometry={nodes['Cylinder 101'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[-330.37, -2.91, 103.58]}
              rotation={[-0.09, -0.17, -1.54]}
              scale={[0.16, 0.67, 0.16]}
            />
            <mesh
              name="Cylinder 415"
              geometry={nodes['Cylinder 415'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[9.35, -9.31, 99.31]}
              rotation={[-0.02, 0.16, -1.43]}
              scale={[0.16, 0.67, 0.16]}
            />
          </group>
          <group name="Group 62" position={[-283.22, 353.53, -39.54]} scale={[-1.01, 1, 1]}>
            <mesh
              name="Sphere 4"
              geometry={nodes['Sphere 4'].geometry}
              material={materials['Color 7']}
              castShadow
              receiveShadow
              position={[25.36, -0.86, -189.19]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={0.42}
            />
            <mesh
              name="Sphere 3"
              geometry={nodes['Sphere 3'].geometry}
              material={materials['Color 6']}
              castShadow
              receiveShadow
              position={[32.4, -0.86, -107.54]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={0.42}
            />
            <mesh
              name="Sphere 2"
              geometry={nodes['Sphere 2'].geometry}
              material={materials['Color 7']}
              castShadow
              receiveShadow
              position={[43.64, -0.86, -27.54]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={0.42}
            />
            <mesh
              name="Sphere1"
              geometry={nodes.Sphere1.geometry}
              material={materials['Color 6']}
              castShadow
              receiveShadow
              position={[54.97, -0.86, 53.03]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={0.42}
            />
            <mesh
              name="Cube 21"
              geometry={nodes['Cube 21'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[-26.27, -3, -19.78]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={[0.7, 1, 0.38]}
            />
            <mesh
              name="Cube1"
              geometry={nodes.Cube1.geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[-27.27, 0, -18.58]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={[0.71, 1.02, 0.38]}
            />
            <mesh
              name="Cylinder 416"
              geometry={nodes['Cylinder 416'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[-5.57, -55.61, 114.41]}
              rotation={[Math.PI / 2, 0, -0.18]}
              scale={0.19}
            />
            <mesh
              name="Cylinder 34"
              geometry={nodes['Cylinder 34'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[-4.27, 13.79, 121.13]}
              rotation={[Math.PI / 2, 0, -0.18]}
              scale={0.27}
            />
          </group>
          <group name="Group 54" position={[246.58, 353.73, -32.05]}>
            <mesh
              name="Sphere 41"
              geometry={nodes['Sphere 41'].geometry}
              material={materials['Color 7']}
              castShadow
              receiveShadow
              position={[25.91, -0.93, -196.12]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={0.42}
            />
            <mesh
              name="Sphere 31"
              geometry={nodes['Sphere 31'].geometry}
              material={materials['Color 6']}
              castShadow
              receiveShadow
              position={[38.41, -0.93, -118.26]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={0.42}
            />
            <mesh
              name="Sphere 21"
              geometry={nodes['Sphere 21'].geometry}
              material={materials['Color 7']}
              castShadow
              receiveShadow
              position={[50.67, -0.93, -31.01]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={0.42}
            />
            <mesh
              name="Sphere2"
              geometry={nodes.Sphere2.geometry}
              material={materials['Color 6']}
              castShadow
              receiveShadow
              position={[61.19, -0.93, 54.89]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={0.42}
            />
            <mesh
              name="Cube 22"
              geometry={nodes['Cube 22'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[-17, 0, -22.78]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={[0.7, 1, 0.38]}
            />
            <mesh
              name="Cube2"
              geometry={nodes.Cube2.geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[-17, 0, -22.78]}
              rotation={[-Math.PI, 1.43, Math.PI / 2]}
              scale={[0.7, 1, 0.38]}
            />
            <mesh
              name="Cylinder 417"
              geometry={nodes['Cylinder 417'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[0.74, -55.61, 114.41]}
              rotation={[Math.PI / 2, 0, -0.18]}
              scale={0.19}
            />
            <mesh
              name="Cylinder 35"
              geometry={nodes['Cylinder 35'].geometry}
              material={materials['Color 3']}
              castShadow
              receiveShadow
              position={[1.88, 13.65, 120.55]}
              rotation={[Math.PI / 2, 0, -0.18]}
              scale={0.27}
            />
          </group>
          <mesh
            name="Cylinder 24"
            geometry={nodes['Cylinder 24'].geometry}
            material={materials['Cylinder 24 Material']}
            castShadow
            receiveShadow
            position={[-9.2, 346.73, 425.21]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.4, 0.25, 0.4]}
          />
          <mesh
            name="Cylinder 16"
            geometry={nodes['Cylinder 16'].geometry}
            material={materials['Color 2']}
            castShadow
            receiveShadow
            position={[-9.2, 346.73, 425.21]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.33, 0.53, 0.33]}
          />
          <mesh
            name="Cylinder4"
            geometry={nodes.Cylinder4.geometry}
            material={materials['Color 3']}
            castShadow
            receiveShadow
            position={[-9.2, 346.73, 425.21]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.47}
          />
          <group name="Group 20" position={[-318.6, -296.21, 573.72]} scale={[-1.23, 1.3, 1.3]}>
            <mesh
              name="Cube 56"
              geometry={nodes['Cube 56'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[4.44, 1.62, 5.54]}
              rotation={[-0.45, 0.26, 0.14]}
              scale={[1.23, 0.78, 0.69]}
            />
            <mesh
              name="Cube 23"
              geometry={nodes['Cube 23'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[4.44, 1.62, 5.54]}
              rotation={[-0.45, 0.26, 0.14]}
              scale={[1.23, 0.78, 0.69]}
            />
            <mesh
              name="Cube 3"
              geometry={nodes['Cube 3'].geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[22.08, -177.87, 59.33]}
              rotation={[-1.47, 0.02, 0.3]}
              scale={[0.81, 0.37, 0.8]}
            />
            <mesh
              name="Cube 64"
              geometry={nodes['Cube 64'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[23.48, -172.22, 63.29]}
              rotation={[-1.44, 0.02, -2.84]}
              scale={[0.62, 0.35, 0.56]}
            />
            <mesh
              name="Cube 41"
              geometry={nodes['Cube 41'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[-17.19, 174.67, -59.02]}
              rotation={[1.17, 0.14, -0.27]}
              scale={[0.88, 0.35, 0.8]}
            />
            <mesh
              name="Cube3"
              geometry={nodes.Cube3.geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[-17.53, 174.13, -60.15]}
              rotation={[1.17, 0.14, -0.27]}
              scale={[0.88, 0.35, 0.8]}
            />
          </group>
          <group
            name="Group 22"
            position={[-441.31, -285.32, -531.33]}
            rotation={[-3.07, -0.36, -3.12]}
            scale={[1.33, 1.27, 0.98]}
          >
            <mesh
              name="Cube 57"
              geometry={nodes['Cube 57'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[4.44, 1.62, 5.54]}
              rotation={[-0.45, 0.26, 0.14]}
              scale={[1.23, 0.78, 0.69]}
            />
            <mesh
              name="Cube 24"
              geometry={nodes['Cube 24'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[4.44, 1.62, 5.54]}
              rotation={[-0.45, 0.26, 0.14]}
              scale={[1.23, 0.78, 0.69]}
            />
            <mesh
              name="Cube 31"
              geometry={nodes['Cube 31'].geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[22.08, -177.87, 59.33]}
              rotation={[-1.47, 0.02, 0.3]}
              scale={[0.81, 0.37, 0.8]}
            />
            <mesh
              name="Cube 65"
              geometry={nodes['Cube 65'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[23.48, -172.22, 63.29]}
              rotation={[-1.44, 0.02, -2.84]}
              scale={[0.62, 0.35, 0.56]}
            />
            <mesh
              name="Cube 42"
              geometry={nodes['Cube 42'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[-17.19, 174.67, -59.02]}
              rotation={[1.17, 0.14, -0.27]}
              scale={[0.88, 0.35, 0.8]}
            />
            <mesh
              name="Cube4"
              geometry={nodes.Cube4.geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[-17.53, 174.13, -60.15]}
              rotation={[1.17, 0.14, -0.27]}
              scale={[0.88, 0.35, 0.8]}
            />
          </group>
          <group
            name="Group 21"
            position={[398.73, -295.73, -540.19]}
            rotation={[-3.06, 0.22, 3.12]}
            scale={[-1.3, 1.27, 1.07]}
          >
            <mesh
              name="Cube 58"
              geometry={nodes['Cube 58'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[4.44, 1.62, 5.54]}
              rotation={[-0.45, 0.26, 0.14]}
              scale={[1.23, 0.78, 0.69]}
            />
            <mesh
              name="Cube 25"
              geometry={nodes['Cube 25'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[4.44, 1.62, 5.54]}
              rotation={[-0.45, 0.26, 0.14]}
              scale={[1.23, 0.78, 0.69]}
            />
            <mesh
              name="Cube 32"
              geometry={nodes['Cube 32'].geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[22.08, -177.87, 59.33]}
              rotation={[-1.47, 0.02, 0.3]}
              scale={[0.81, 0.37, 0.8]}
            />
            <mesh
              name="Cube 66"
              geometry={nodes['Cube 66'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[23.48, -172.22, 63.29]}
              rotation={[-1.44, 0.02, -2.84]}
              scale={[0.62, 0.35, 0.56]}
            />
            <mesh
              name="Cube 43"
              geometry={nodes['Cube 43'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[-17.19, 174.67, -59.02]}
              rotation={[1.17, 0.14, -0.27]}
              scale={[0.88, 0.35, 0.8]}
            />
            <mesh
              name="Cube5"
              geometry={nodes.Cube5.geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[-17.53, 174.13, -60.15]}
              rotation={[1.17, 0.14, -0.27]}
              scale={[0.88, 0.35, 0.8]}
            />
          </group>
          <group name="Group1" position={[280.71, -296.21, 573.72]} scale={1.3}>
            <mesh
              name="Cube 59"
              geometry={nodes['Cube 59'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[4.44, 1.62, 5.54]}
              rotation={[-0.45, 0.26, 0.14]}
              scale={[1.23, 0.78, 0.69]}
            />
            <mesh
              name="Cube 26"
              geometry={nodes['Cube 26'].geometry}
              material={materials['Color 2']}
              castShadow
              receiveShadow
              position={[4.44, 1.62, 5.54]}
              rotation={[-0.45, 0.26, 0.14]}
              scale={[1.23, 0.78, 0.69]}
            />
            <mesh
              name="Cube 33"
              geometry={nodes['Cube 33'].geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[22.08, -177.87, 59.33]}
              rotation={[-1.47, 0.02, 0.3]}
              scale={[0.81, 0.37, 0.8]}
            />
            <mesh
              name="Cube 67"
              geometry={nodes['Cube 67'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[23.48, -172.22, 63.29]}
              rotation={[-1.44, 0.02, -2.84]}
              scale={[0.62, 0.35, 0.56]}
            />
            <mesh
              name="Cube 44"
              geometry={nodes['Cube 44'].geometry}
              material={materials['Color 1']}
              castShadow
              receiveShadow
              position={[-17.19, 174.67, -59.02]}
              rotation={[1.17, 0.14, -0.27]}
              scale={[0.88, 0.35, 0.8]}
            />
            <mesh
              name="Cube6"
              geometry={nodes.Cube6.geometry}
              material={materials['Color 5']}
              castShadow
              receiveShadow
              position={[-17.53, 174.13, -60.15]}
              rotation={[1.17, 0.14, -0.27]}
              scale={[0.88, 0.35, 0.8]}
            />
          </group>
        </group>
        <hemisphereLight name="Default Ambient Light" intensity={0.35} color="#eaeaea" />
      </group>
    </>
  )
}
